### ISSUE TITLE
MSBuild locator does not include Jetbrains MSBuild

### ISSUE THREAD

**Issue by nojaf** [ionide/dotnet-proj-info#33]
Hi @enricosada I'm trying the following code:

```fsharp
MSBuildLocator()
|> fun ml -> ml.InstalledMSBuilds()
```

it returns 

```fsharp
  [Path
     "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin\MsBuild.exe";
   Path "c:\Windows\Microsoft.NET\Framework\v4.0.30319\MsBuild.exe";
   Path "c:\Windows\Microsoft.NET\Framework\v3.5\MsBuild.exe"]
```

however I do have the [JetBrains MSBuild](https://blog.jetbrains.com/dotnet/2018/04/13/introducing-jetbrains-redistributable-msbuild/) installed as well. It should have added `C:\Program Files\Jetbrains\MSBuild\15.0\Bin\MSBuild.exe` to the list as well I guess.
Note that `Program Files\Jetbrains\MSBuild` is a location of my own choosing.

Is there any way to include this path?

**Comment by enricosada** [comment]
So the path is not fixed, so we cannot guess.

Afaik we cannot guess unless there is a registry or something like that (but seems unlikely, because install it's just a zip and configured in rider).

That method `InstalledMSBuilds` is useful to show default known locations, so user can choose.

If you know the location, you can override that

```fsharp
let config =
	{ LoaderConfig.Default(msbuildLocator) with
           MSBuildHost = MSBuildExePath.Path @"C:\Program Files\Jetbrains\MSBuild\15.0\Bin\MSBuild.exe" }
```

But i this think cannot be done for the users, because need anyway to set something (an env var?)

I think it's possibile to:

- check also the PATH for `msbuild.exe`, and rider users need to just add that directory to PATH once.
- consumers set it, like in FSAC/ionide, asking the user and setting the path in  `LoaderConfig.MSBuildHost`

Or find a way to read rider config, if exists

I dont like to add a config file for this library, i think consumer should instead use their config file.

**Comment by Krzysztof-Cieslak** [comment]
We're now using official Locator provided by `Microsoft.Build.Locator` package
